cmake_minimum_required(VERSION 3.31)
project(discusy_examples LANGUAGES CXX)

add_subdirectory(slash_commands)
add_subdirectory(components)
add_subdirectory(components_with_when)
if(DISCUSY_ENABLE_VOICE)
    add_subdirectory(voice)
endif()
add_subdirectory(receiving_events)
add_subdirectory(updating_presences)
add_subdirectory(multithreading)
add_subdirectory(using_completion_tokens)
add_subdirectory(random_image_bot)
